[package]
name = "deterministic_svm"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { workspace = true }
bs58 = { workspace = true }
byteorder = { workspace = true }
enum-iterator = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
num-traits = { workspace = true }
percentage = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
solana-sbpf = { workspace = true }
