[package]
name = "block_builder"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { workspace = true }
solana-sdk = { workspace = true }
solana-account = { workspace = true, features = ["bincode"] }
merkle_tree = { path = "../merkle_tree" }
